### ISSUE TITLE
Documentation not working take 2

### ISSUE THREAD

**Issue by cpgr** [cpgr/numbat#2]
Although the website builds now, I have these types of things strewn throughout

<img width="874" alt="auxkerlens" src="https://user-images.githubusercontent.com/7664823/32098118-65152bcc-bb57-11e7-9cc4-6b55a6f99e0d.png">

Something isn't working properly for me. Sorry again @aeslaughter, but what am I missing?

**Comment by aeslaughter** [comment]
The [material-icons](https://github.com/idaholab/moose/tree/devel/docs/content/contrib/fonts/material-icons) icon package is not being loaded correctly. What browser and version are you using? There is chance that your browser doesn't support the font. 
There could be a problem when coping the files to the site build directory, you can use your browser developer tools to look at dependencies to see if they are missing.

These contrib css/js/fonts are copied to your site in [build.py](https://github.com/idaholab/moose/blob/devel/python/MooseDocs/commands/build.py#L88), you could put some print statements to make sure they are correct.

**Comment by cpgr** [comment]
Thanks for the hint. The culprit was an old moose.css file that had been copied over to my repository. Once that was removed moosedocs found material-icons.

Thanks again for this system, it makes building a documentation website very easy!
