### ISSUE TITLE
Add numbat to moose tests

### ISSUE THREAD

**Issue by cpgr** [cpgr/numbat#3]
Hi @brianmoose

Is it possible to get this app added to the tests that get run so that I can get little things like the change  in idaholab/moose#10445 patched. This hit me today when I updated the moose install on our cluster and broke this app.

Thanks,
Chris

**Comment by brianmoose** [comment]
Sure, it wouldn't be a problem if @permcody agrees?

**Comment by permcody** [comment]
Yes, please add it.

**Comment by brianmoose** [comment]
OK, I have added numbat to the "External App tests" on MOOSE PRs.

**Comment by cpgr** [comment]
Thanks!
