### ISSUE TITLE
2Darithmetic_action and 2Dharmonic_action test failures

### ISSUE THREAD

**Issue by brianmoose** [cpgr/numbat#4]
```
FAIL effective_permeability.2Darithmetic_action FAILED (ERRMSG)
FAIL effective_permeability.2Dharmonic_action FAILED (ERRMSG)
```
Both have error message: `A 'NumbatEffectivePermeabilityAction' is not a registered Action`

https://civet.inl.gov/job/205177/

**Comment by cpgr** [comment]
Oops, looks like I forgot to commit the actual .h and .C files for this action. 

It should be fixed now
